# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Rob Garth
tagline:             'Mildly Useful Stuff'
description:         Rob Garth
url:                 https://rgarth.github.io
baseurl:             ''
paginate:            5
gems:                [jekyll-paginate]
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/3967805?s=400&u=e6888bdec4641d904582a7caa1ad34de1a4c2ac0&v=4

# About/contact
author:
  name:              Rob Garth
  url:               https://twitter.com/rgarth
  email:             rgarth@gmail.com

# Custom vars
version:             1.0.0
