# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Rob Garth
tagline:             'Mildly Useful Stuff'
description:         Rob Garth
url:                 https://rgarth.github.io
baseurl:             ''
paginate:            5
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Rob Garth
  url:               https://twitter.com/rgarth
  email:             rgarth@gmail.com

# Custom vars
version:             1.0.0
